@startuml

start

:Get the entry's type;

:Get the invalidation strategy
corresponding to the entry type;

if (strategy == null) then (yes)
	:No invalidation required by the
	processor for this entry;
else (no)
	:Invalidate the entry
	using the strategy found;
endif

:Send the entry to the next processor;

stop

@enduml